title = "DokChess (arc42)"
baseURL = "https://www.dokchess.de/"

languageCode = "de-de"
defaultContentLanguage = "de"

theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
  disableShortcutsTitle=true

[Blackfriday]
hrefTargetBlank=true

[Languages]
[Languages.de]
title = "DokChess (arc42)"
weight = 1
languageName = "Deutsch"

[Languages.en]
title = "DokChess (arc42)"
weight = 2
languageName = "English"


[[menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> Über den Autor"
url = "/autor/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-star'></i> Abspann (Credits)"
url = "/abspann/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Quelltexte (GitHub)"
identifier = "ds"
url = "https://github.com/DokChess/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Impressum"
url = "/impressum/"
weight = 13

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> About the autor"
url = "/author/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-star'></i> Credits"
url = "/credits/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Source code (GitHub)"
identifier = "ds"
url = "https://github.com/DokChess/"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Site Notice"
url = "/site_notice/"
weight = 13
