baseURL = "http://www.dokchess.de/"
languageCode = "de-de"
title = "DokChess"
theme = "learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"

  disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> Über den Autor"
url = "/autor/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Quelltexte (GitHub)"
identifier = "ds"
url = "https://github.com/DokChess/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-star'></i> Abspann"
url = "/abspann/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Impressum"
url = "/impressum/"
weight = 13
